---

- include: prerequisites.yml
  when: zammad_install_prerequisites

- include: zammad_user.yml
  when: zammad_user_group_create

- include: nginx_setup.yml
  when: zammad_install_nginx

- include: zammad_setup.yml
  when: zammad_install

- include: zammad_configure.yml
  when: zammad_configure

- include: zammad_database.yml
  when: zammad_initialize_db

- include: nginx_configure.yml
  when: zammad_configure_nginx
