---

- name: Execute database setup commands
  shell: "bundle exec rake {{ item }}"
  args:
    chdir: /opt/zammad
  environment:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
  with_items:
    - db:create
    - db:migrate
    - db:seed
    - assets:precompile
