---

- name: Execute database setup commands
  shell: "{{ item }}"
  args:
    chdir: /opt/zammad
  environment:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
  with_items:
    - rake db:create
    - rake db:migrate
    - rake db:seed
    - rake assets:precompile
