---

- name: Execute database setup commands
  shell: "{{ item }}"
  args:
    chdir: /opt/zammad
  with_items:
    - rake db:create
    - rake db:migrate
    - rake db:seed
    - rake assets:precompile
